--- #YAML:1.0
name: DBIx-LogAny
abstract: Log all Perl DBI calls Log::LogAny
version: '0.06'
version_from: lib/DBIx/Log4perl.pm
author:
  - 'Martin J. Evans <mjevans@cpan.org>'
license: perl
distribution_type: module
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
requires:
    DBI:                           '1.5'
    Log::LogAny:                   '0.04'
    Test::More:                    '0.62'
    Scalar::Util:                  '0'
    File::Spec:                    '0'
    Log::Any::Adapter:             '0.1'
    Data::Dumper:                  '0'
build_requires:
  DBI: 1.21
configure_requires:
  DBI: 1.21
resources:
  license: http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DBIx-LogAny
  repository: https://github.com/mjegh/DBIx-LogAny.git
installdirs:  site
keywords:
  - DBI
  - DBD
  - DBIx
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Martin J. Evans
# ensure there is a newline at the end of this file or pause objects

