--- #YAML:1.0
name: DBIx-LogAny
abstract: Log all Perl DBI calls Log::Any
version: 0.02
version_from: lib/DBIx/LogAny.pm
author:
  - Martin J. Evans
license: perl
distribution_type: module
requires:
    DBI:                           1.5
    Log::Any:                 0.14
    Test::More:                    0.62
    Log::Any::Adapter: 0.10
    Data::Dumper: 0
    File::Spec: 0
    Module::Loaded: 0
build_requires:
  DBI: 1.21
configure_requires:
  DBI: 1.21
resources:
  license: http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DBIx-LogAny
  repository: https://github.com/mjegh/DBIx-LogAny.git
  MailingList: http://dbi.perl.org/support
installdirs:  site
keywords:
  - DBI
  - DBD
  - DBIx
  - logging
  - tracing
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Martin J. Evans
# ensure there is a newline at the end of this file or pause objects
